import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("prospect").del();

  // Inserts seed entries
  await knex("prospect").insert([
    // Generated from mockaroo
    // https://www.mockaroo.com/schemas/353761
    {
      activated: false,
      t_number: "T-00003338",
      first_name: "Clemmy",
      middle_name: "Theresina",
      last_name: "Spires",
      term: "Spring",
      level: "Freshman",
      primary_program_id: 25,
      secondary_program_id: 35,
      decision: "Applicant In-Progress",
      admit_date: "11/19/2020",
      street_address_1: "081 Ludington Park",
      street_address_2: "Almo",
      street_address_3: "68983",
      city: "Los Angeles",
      state: "California",
      zip_code: "20118",
      phone_number: "323-895-4523",
      email_address: "tspires0@nsw.gov.au",
      ualr_email: "be429@ualr.edu",
      sex: "Male",
      ethnicity: "Central American",
      admission_type: "Reapplicant",
      student_type: "Freshman w/ college credit",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00050675",
      first_name: "Briggs",
      middle_name: "Angelita",
      last_name: "Criple",
      term: "Spring",
      level: "Senior",
      primary_program_id: 36,
      secondary_program_id: 43,
      decision: "Applicant Accepted",
      admit_date: "12/5/2021",
      street_address_1: "710 Longview Court",
      street_address_2: "Mccormick",
      street_address_3: "08425",
      city: "Des Moines",
      state: "Iowa",
      zip_code: "74666",
      phone_number: "515-847-8794",
      email_address: "acriple1@arstechnica.com",
      ualr_email: "by426@ualr.edu",
      sex: "Female",
      ethnicity: "Yuman",
      admission_type: "Freshman",
      student_type: "Returning Student",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00019931",
      first_name: "Carlotta",
      middle_name: "Ondrea",
      last_name: "Cranmer",
      term: "Summer",
      level: "Sophomore",
      primary_program_id: 59,
      secondary_program_id: 39,
      decision: "Applicant In-Progress",
      admit_date: "10/3/2021",
      street_address_1: "03311 Blaine Street",
      street_address_2: "Truax",
      street_address_3: "74708",
      city: "Washington",
      state: "District of Columbia",
      zip_code: "54601",
      phone_number: "202-231-2478",
      email_address: "ocranmer2@go.com",
      ualr_email: "be167@ualr.edu",
      sex: "Male",
      ethnicity: "Paiute",
      admission_type: "Reapplicant",
      student_type: "Transfer",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00007584",
      first_name: "Bunnie",
      middle_name: "Fleming",
      last_name: "Strattan",
      term: "Fall",
      level: "Freshman",
      primary_program_id: 38,
      secondary_program_id: 23,
      decision: "Admitted-File Incomplete",
      admit_date: "9/29/2021",
      street_address_1: "309 Westport Place",
      street_address_2: "Kinsman",
      street_address_3: "10042",
      city: "Whittier",
      state: "California",
      zip_code: "40210",
      phone_number: "562-232-2080",
      email_address: "fstrattan3@pen.io",
      ualr_email: "an529@ualr.edu",
      sex: "Male",
      ethnicity: "Chinese",
      admission_type: "Transfer",
      student_type: "Freshman w/ college credit",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00051177",
      first_name: "Jasun",
      middle_name: "Ware",
      last_name: "Sammars",
      term: "Summer",
      level: "Senior",
      primary_program_id: 61,
      secondary_program_id: 27,
      decision: "Admitted-File Incomplete",
      admit_date: "2/5/2021",
      street_address_1: "2 Springs Point",
      street_address_2: "Redwing",
      street_address_3: "83463",
      city: "Fort Lauderdale",
      state: "Florida",
      zip_code: "63290",
      phone_number: "954-326-8504",
      email_address: "wsammars4@admin.ch",
      ualr_email: "Mr104@ualr.edu",
      sex: "Male",
      ethnicity: "Ecuadorian",
      admission_type: "Reapplicant",
      student_type: "Transfer",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00068465",
      first_name: "Andree",
      middle_name: "Sibley",
      last_name: "Combe",
      term: "Spring",
      level: "Sophomore",
      primary_program_id: 50,
      secondary_program_id: 56,
      decision: "Applicant In-Progress",
      admit_date: "12/29/2021",
      street_address_1: "08277 Rockefeller Junction",
      street_address_2: "Ridge Oak",
      street_address_3: "09911",
      city: "Chicago",
      state: "Illinois",
      zip_code: "45230",
      phone_number: "773-134-5685",
      email_address: "scombe5@yolasite.com",
      ualr_email: "oh846@ualr.edu",
      sex: "Male",
      ethnicity: "Indonesian",
      admission_type: "Transfer",
      student_type: "First-time Freshman",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00083839",
      first_name: "Ced",
      middle_name: "Stavros",
      last_name: "O'Drought",
      term: "Spring",
      level: "Sophomore",
      primary_program_id: 8,
      secondary_program_id: 60,
      decision: "Applicant Accepted",
      admit_date: "5/27/2021",
      street_address_1: "3301 Beilfuss Point",
      street_address_2: "Farragut",
      street_address_3: "27965",
      city: "Wilmington",
      state: "Delaware",
      zip_code: "69207",
      phone_number: "302-330-6848",
      email_address: "sodrought6@mashable.com",
      ualr_email: "pi377@ualr.edu",
      sex: "Male",
      ethnicity: "Fijian",
      admission_type: "Transfer",
      student_type: "Transfer",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00030280",
      first_name: "Stevy",
      middle_name: "Tammie",
      last_name: "Danis",
      term: "Summer",
      level: "Senior",
      primary_program_id: 55,
      secondary_program_id: 33,
      decision: "Applicant Accepted",
      admit_date: "9/4/2021",
      street_address_1: "9731 Fuller Junction",
      street_address_2: "Havey",
      street_address_3: "35812",
      city: "New York City",
      state: "New York",
      zip_code: "39214",
      phone_number: "917-977-5090",
      email_address: "tdanis7@gravatar.com",
      ualr_email: "mu617@ualr.edu",
      sex: "Female",
      ethnicity: "Panamanian",
      admission_type: "Freshman",
      student_type: "Freshman w/ college credit",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00003559",
      first_name: "Duane",
      middle_name: "Corliss",
      last_name: "Trammel",
      term: "Fall",
      level: "Senior",
      primary_program_id: 47,
      secondary_program_id: 31,
      decision: "Applicant In-Progress",
      admit_date: "12/25/2021",
      street_address_1: "139 Grasskamp Lane",
      street_address_2: "Sugar",
      street_address_3: "24511",
      city: "Miami",
      state: "Florida",
      zip_code: "42428",
      phone_number: "786-812-5453",
      email_address: "ctrammel8@cpanel.net",
      ualr_email: "ad870@ualr.edu",
      sex: "Female",
      ethnicity: "Indonesian",
      admission_type: "Reapplicant",
      student_type: "Freshman w/ college credit",
      campaign_id: 1,
    },
    {
      activated: false,
      t_number: "T-00009419",
      first_name: "Ebeneser",
      middle_name: "Layla",
      last_name: "Matresse",
      term: "Fall",
      level: "Freshman",
      primary_program_id: 38,
      secondary_program_id: 24,
      decision: "Applicant Accepted",
      admit_date: "10/9/2021",
      street_address_1: "216 Summerview Park",
      street_address_2: "Tennessee",
      street_address_3: "19528",
      city: "Sioux Falls",
      state: "South Dakota",
      zip_code: "88497",
      phone_number: "605-711-8163",
      email_address: "lmatresse9@jalbum.net",
      ualr_email: "he227@ualr.edu",
      sex: "Female",
      ethnicity: "Lumbee",
      admission_type: "Transfer",
      student_type: "Transfer",
      campaign_id: 1,
    },
  ]);
}
